services:
  frontend:
    build:
      context: ./frontend
    container_name: conta-certa-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: conta-certa-backend
    ports:
      - "4000:4000"
    restart: unless-stopped

